name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        with:
          branch: main
          working_directory: ./Packages/EasyHttpRPC
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy docs
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          cp README.md Packages/EasyHttpRPC/
          cp LICENSE Packages/EasyHttpRPC/
          cp Packages/EasyHttpRPC/CHANGELOG.md ./

      - name: Commit
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          git config user.name github-actions
          git config user.email action@github.com
          git add .
          git commit -m ${{ steps.semantic.outputs.new_release_version }}
          git tag -d v${{ steps.semantic.outputs.new_release_version }}
          git push --delete origin v${{ steps.semantic.outputs.new_release_version }}
          git tag v${{ steps.semantic.outputs.new_release_version }}
          git push
          git push --tags
