name: release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        with:
          branch: main
          working_directory: ./Packages/EasyHttpRPC
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    
